### PR TITLE
 Add optional setting PASSWORD_VALIDATORS 

### PR DESCRIPTION
**Pull request by sh4r3m4n**
By default it's an empty list. When it has values, the password changes serializers validate the new password against the given validators.
Very useful with [django-passwords](https://github.com/dstufft/django-passwords/blob/master/passwords/validators.py) validators module.

### CODE REVIEW

**Comment by sh4r3m4n** [comment]
I updated this to pass the tests with django<1.7

**Comment by haxoza** [comment]
Nice, good idea! And thanks for your pull request. It looks good so we would be happy to merge it. 

However it would be good to add at least one test to our test suite that overrides the password validators setting.

**Comment by sh4r3m4n** [comment]
Ok, I will code some tests the next days

**Comment by mmarksnippety** [comment]
Thanks for your pull request. We plans to merge #117 that are derived from yours pull.

**Pull request closed without merging**
