### PR TITLE
Add configurable password validators

### PR DESCRIPTION
**Pull request by lwm**
Based on the awesome work of #86, but instead of passing absolute path strings for validators, you just pass the functions (closer to DRF way?) and has some tests.

If this PR goes in, would close #86 and #107.

### CODE REVIEW

**Comment by lwm** [comment]
Problem seems related to [#5485](https://github.com/travis-ci/travis-ci/issues/5485), will try to add a fix.

**Comment by lwm** [comment]
Reverted my fix for Travis, as it is covered from #123, and rebased on master.

**Comment by mmarksnippety** [comment]
Your changes are merged in #124. I added one test, and rebase to master.
The new version (0.4.2) will be released today.

**Comment by lwm** [comment]
Thanks! :rocket:

**Pull request closed without merging**
