### PR TITLE
djoser returns a HTTP 400 for a stale activation token

### PR DESCRIPTION
**Pull request by lwm**
Hi folks, I assume this should be standard behaviour so I went ahead and wrote it. 

Let me know what you think :+1:

### CODE REVIEW

**Comment by haxoza** [comment]
Thanks! At first glance it looks good.

Do you think that it is really necessary to detect situation when the activation URL was reached for the second time?

**Comment by lwm** [comment]
Cool, happy to help.

As for as I understand it, firing a `POST` request at the `/activate/` end-point is idempotent. However, in terms of user experience, a reason could be that if the user clicks the link and something bad happens (browser drops, tab closes, etc.) and they are not sure what the result was, they can try to click the activation link again and they will be told that it is invalid.

**Comment by lwm** [comment]
Oh, and as noted by a colleague, perhaps returning a `419` response would be better, as noted in [#158](https://github.com/GetBlimp/django-rest-framework-jwt/issues/158#issuecomment-161930536).

**Comment by haxoza** [comment]
@lwm Thanks for your work. I've just merged the PR but we decided that 403 response status code is more suitable in this situation. If 419 would be used for libraries like DRF-JWT I can imagine that it could interfere with authentication mechanisms on the client side.

However after long discussion we are still not sure if the 400 code is just even better.

**Comment by lwm** [comment]
@haxoza Sounds good :rocket:

**Pull request closed without merging**
