### PR TITLE
add django 3.2 support

### LINKED ISSUE #628: Support Django 3.2
This project currently declares support for Django 3 up to 3.1: it would be great if it could also officially support 3.2, since that's now the latest LTS version.

### PR DESCRIPTION
**Pull request by umarmughal824**
fixes #628 
add django 3.2 support

### CODE REVIEW

**Comment by umarmughal824** [comment]
@haxoza could you please take a look on my PR

**Comment by allanlewis** [comment]
Thanks for merging this, @dekoza 🙏 
Is there a plan to release a new version, if only for the dependency changes?

**Comment by dekoza** [comment]
@allanlewis yes, I'll make a release this week after I merge most of the PRs. Thanks for your work and patience :slightly_smiling_face:

**Comment by umarmughal824** [comment]
@dekoza could you please add a new version tag release for it?

**Comment by asadiqbal08** [comment]
@dekoza is that released ?

**Pull request merged**
