### PR TITLE
#54 change wrong setting in Register section in readme

### PR DESCRIPTION
**Pull request by gitfred**
Changed `LOGIN_AFTER_ACTIVATION` to `LOGIN_AFTER_REGISTRATION` and remove some whitespaces in `README`

### CODE REVIEW

**Comment by haxoza** [comment]
Awesome! Thanks! :+1:

**Comment by mcgeeco** [comment]
I implemented a login after activation myself, would that be a worthwhile feature?

**Comment by konradhalas** [comment]
As I remember (@haxoza correct me if I'm wrong), we have plans to remove all `LOGIN_AFTER_*` settings, because 1) those settings increase code complexity too much, 2) you could just make login request after registration/activation. Does it make sense?

**Comment by mcgeeco** [comment]
Yeah I suppose it makes sense to keep the complexity down, otherwise you could start implementing login after for everything.

**Comment by konradhalas** [comment]
Indeed. Thanks.

**Pull request merged**
