### PR TITLE
RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated …

### PR DESCRIPTION
**Pull request by ashishmohite**
Issue link : [https://github.com/sunscrapers/djoser/issues/101]

RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10 #101

- resolve the warning
- remove pylint errors from urls files

### CODE REVIEW

**Comment by borfast** [comment]
Just tested this and it seems to be working fine. Could a maintainer review and merge, please?

**Comment by jgirdner** [comment]
This looks like it fixed the depreciation issues on urls.  Can someone please merge this in?

**Comment by mmarksnippety** [comment]
We working on Django 1.9 compatibility. We are planning a new release this week

**Comment by mmarksnippety** [comment]
Thank you for your pull request. 
After a offline survey in Sunscrapers, we decided to not change the urls formatting.
I close this pull request, because requested problem is solved in #123

**Pull request closed without merging**
