### PR TITLE
Add namespace to djoser urls to prevent url clashes

### PR DESCRIPTION
**Pull request by mcastle**
Prevents url clashes with Django urls and other lib urls. This fixes issue #60.

### CODE REVIEW

**Comment by lwm** [comment]
Any movement on this? Seems to make sense, as some of the names are quite general, for example, `register`, `user`, `login`.

**Comment by mmarksnippety** [comment]
Adding namespace breaks compatibility. So we plan to add it in the next major release. First we release minro version with fixes to Django 1.9

**Comment by lwm** [comment]
> So we plan to add it in the next major release.

:rocket:

**Comment by mmarksnippety** [comment]
I make pull request #129. It introduce configurable url namespace.

**Pull request closed without merging**
