### PR TITLE
Add CONSTANTS option to settings

### PR DESCRIPTION
**Pull request by mrouhi13**
User now customize messages and add new constants.

### CODE REVIEW

**Comment by joshua-s** [comment]
These settings would be very useful!

**Comment by mrouhi13** [comment]
@joshua-s any problem to merge this pull request?

**Comment by joshua-s** [comment]
I actually don't have permissions on this repo. @dekoza?

**Comment by alexandernst** [comment]
Can we get this merged @dekoza ?

**Comment by mrouhi13** [comment]
@alexandernst I created a new PR and accepted, but I'm late for new release (1.6.0), but I hope in the next release you can have this feature.

**Pull request closed without merging**
