### PR TITLE
Version 2.0

### PR DESCRIPTION
**Pull request by joshua-s**
This is an updated copy of #259

### CODE REVIEW

**Comment by alexandernst** [comment]
@dekoza can we help somehow push this forward?

**Comment by alexandernst** [comment]
@joshua-s @dekoza ping

**Comment by joshua-s** [comment]
I propose that we merge this into a v2 branch so that we can all collaborate on it.

**Comment by alexandernst** [comment]
@joshua-s @dekoza ping

**Comment by joshua-s** [comment]
@alexandernst I do not have write access, so am waiting as well on this

**Comment by dekoza** [comment]
OK, I've made a new branch: `v2` as suggested - please disregard branch `version-2.0` :wink:

**Comment by dekoza** [comment]
Last note: Let's tag PRs with [v2] to instantly show that they reference `v2` branch.

**Pull request closed without merging**
