### PR TITLE
views: use @action(detail=False) instead of deprecated @list_route

### PR DESCRIPTION
**Pull request by blueyed**
Fixes:

> …/djoser/views.py:336: PendingDeprecationWarning:
> `list_route` is pending deprecation and will be removed in 3.10 in
> favor of `action`, which accepts a `detail` bool. Use `@action(detail=False)`
> instead.

Have not checked if it works with all supported DRF versions, but CI should tell us.

### CODE REVIEW

**Comment by dekoza** [comment]
It doesn't work with DRF 3.7. Since DRF has no LTS version we try to keep compatibility with both current and previous minor version. When DRF 3.9 shows up, we'll drop support for DRF 3.7 and this PR will stop failing :wink:

**Comment by dekoza** [comment]
It's not - mainly because [DRF takes care of handling `@list_route` and `@detail_route` properly ](https://github.com/encode/django-rest-framework/blob/master/rest_framework/decorators.py#L224)

**Comment by blueyed** [comment]
Yeah.. it was meant to avoid the pendingdeprecationwarning, but I assume that does not make sense given that it is pending..?!

**Comment by jaap3** [comment]
3.9 has been released, so maybe reopen this?

**Pull request closed without merging**
