### PR TITLE
Add support for Drf 3.5

### LINKED ISSUE #171: Incompatible with schema generation of DRF 3.5.0
Hi,
I updated DRF to 3.5.0 and encountered a problem with Djoser. DRF is unable to generate schema because of this line: https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/schemas.py#L387

As you can see it's trying to get action attr from the method, however, Djoser, of course, returns a method as it implements methods with this name. As a result, I got 
`TypeError: getattr(): attribute name must be string`

The whole stack trace:
```
Internal Server Error: /docs/
Traceback (most recent call last):
  File "/home/app/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/app/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/app/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/app/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/app/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/app/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/app/local/lib/python2.7/site-packages/rest_framework/views.py", line 477, in dispatch
    response = self.handle_exception(exc)
  File "/home/app/local/lib/python2.7/site-packages/rest_framework/views.py", line 437, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/app/local/lib/python2.7/site-packages/rest_framework/views.py", line 474, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/app/local/lib/python2.7/site-packages/rest_framework/schemas.py", line 579, in get
    schema = generator.get_schema(request)
  File "/home/app/local/lib/python2.7/site-packages/rest_framework/schemas.py", line 229, in get_schema
    links = self.get_links(request)
  File "/home/app/local/lib/python2.7/site-packages/rest_framework/schemas.py", line 258, in get_links
    link = self.get_link(path, method, view)
  File "/home/app/local/lib/python2.7/site-packages/rest_framework/schemas.py", line 366, in get_link
    description = self.get_description(path, method, view)
  File "/home/app/local/lib/python2.7/site-packages/rest_framework/schemas.py", line 388, in get_description
    method_docstring = getattr(view, method_name, None).__doc__
TypeError: getattr(): attribute name must be string
```
Not really sure what to do. Any advice?

Thanks.

### PR DESCRIPTION
**Pull request by ticosax**
This PR essentialy rename `View.action` into `View._action` because `View.action` is a reserved attribute of DRF.

https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/request.py#L56

This change is potentially backward incompatible, as such, a changelog entry should explain the steps and/or published with a major version bump (at the appreciation of the maintainers).

fixes #171

### CODE REVIEW

**Comment by juliomfreitas** [comment]
nice! we really need this PR accepted! Thanks

**Comment by ticosax** [comment]
Thank you for merging.
My commits were on purpose separated because, I believe, they served a different meaning.
I'll try to keep it in mind for next time though :smile:

**Comment by lerrua** [comment]
@piotr-szpetkowski is it possible to you guys generate a minor version with this patch?

**Comment by slav0nic** [comment]
yep, waiting it too

**Comment by mackeyja92** [comment]
When will the patch be available?

**Comment by piotr-szpetkowski** [comment]
@lerrua @slav0nic @mackeyja92
We will release new Djoser version in a period of one week. I apologize for the trouble.
In the meantime there are two options to workaround the issue:

- If you really need the new features from DRF 3.5 you could simply install djoser from git (and test the upcoming release for issues if there would be any :smile:) with following command in your shell:  
`pip install git+git://github.com/sunscrapers/djoser.git@0ae8df1`
- Otherwise if you do not need the new features right now you could downgrade your DRF to 3.4.7 with:  
`pip install djangorestframework==3.4.7`

**Comment by haxoza** [comment]
We are sorry that it took so much time but it is finally there!

https://pypi.python.org/pypi/djoser/0.5.2

**Pull request merged**
