### PR TITLE
No content is coming back, so it should be 204

### LINKED ISSUE #118: djoser should return 204 instead of 200
In the following views:

  * `LogoutView`, 
  * `PasswordResetView`, 
  * `SetPasswordView`, 
  * `PasswordResetConfirmView`, 
  * `ActivationView`
  * `SetUsernameView`

`djoser` returns a `HTTP_200_OK` 

```
return response.Response(status=status.HTTP_200_OK)
```

but there is no content, so it should be a `HTTP_204_NO_CONTENT`:

```
return response.Response(status=status.HTTP_204_NO_CONTENT)
```

### PR DESCRIPTION
**Pull request by lwm**
Closes #118.

### CODE REVIEW

**Comment by lwm** [comment]
Failing due to an existing problem with your Travis build. I added a fix in #117, see the comment [here](https://github.com/sunscrapers/djoser/pull/117#issuecomment-180390261).

**Comment by mmarksnippety** [comment]
Fix to Travis build is included in #123.

**Comment by lwm** [comment]
> Fix to Travis build is included in #123.

Awesome. Rebased onto master :+1:

**Comment by hvdklauw** [comment]
Awesome, I was just notified of this issue by our frontend developer !
Any ETA on a merge and release?

**Comment by haxoza** [comment]
We would be happy to merge it but we're still wondering what is the exact reason of having it from frontend developer point of view.

@hvdklauw can you give us some examples / rationales?

**Comment by mcgeeco** [comment]
From what I understand from our front-end guys, angular.js always looks for content from a 200/201, so that was causing them some issues in our case.

**Comment by hvdklauw** [comment]
It makes sense, the 204 no content is meant for when you have no content to return. the github/fetch library also breaks on a 200 response having no body

**Comment by lwm** [comment]
@mmarksnippety 

I think we have received valid reasons from front-end'ers. 

Apologies for being pushy, but, well, you know :+1:

**Comment by haxoza** [comment]
Merged! 🎉

**Pull request closed without merging**
